version: 2.1
jobs:
  build-and-push-image:
    docker:
      - image: cimg/node:20.3.1
    steps:
      - checkout
      - setup_remote_docker:
      - run:
          name: Build and push image
          command: |
            version="build-$CIRCLE_BUILD_NUM"
            echo $version
            docker build -t paularinze/reddit-clone:$version .
            echo $DOCKER_PASSWORD | docker login -u paularinze --password-stdin
            docker push paularinze/reddit-clone:$version
  Update_manifest:
    docker:
      - image: cimg/base:2023.06
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Updating Manifest file 
          command: |
            TAG=$CIRCLE_BUILD_NUM
            ((TAG--))
            git clone https://github.com/paularinzee/kube-manifest.git
            git config --global user.email "arinzennajipaul@gmail.com"
            git config --global user.name "paularinzee"
            pwd
            cd kube_manifest
            pwd
            echo $TAG
            sed -i "s/build-.*/build-$TAG/g" manifest/deployment.yaml
            cat manifest/deployment.yaml
            git add .
            git commit -m "new build with imgTag build-$TAG"
            git config credential.helper 'cache --timeout=120'
            git push -q https://$GITHUB_PERSONAL_TOKEN@github.com/paularinzee/kube-manifest.git master 

workflows:
  the_jobs:
    jobs:
      - build-and-push-image
      - Update_manifest:
          requires:
            - build-and-push-image
          
    
  